services:
  - type: web
    name: marvel-auction-wars-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        sync: false
