import { Character, Faction, SynergyBonus } from '../types/game';

// Comprehensive Marvel Character Faction Mapping
export const FACTION_MEMBERS: Record<Faction, string[]> = {
  'Avengers': [
    'Iron Man', 'Captain America', 'Thor', 'Thor Odinson', 'Hulk', 'Hawkeye', 'Black Widow', 
    'Scarlet Witch', 'Vision', 'War Machine', 'Falcon', 'Ant-Man', 'Janet Van Dyne', 'Hank Pym',
    'Captain Marvel', 'Spider-Man', 'Doctor Strange', 'Black Panther', 'Quicksilver', 
    'Wonder Man', 'She-Hulk', 'Shang-Chi', 'Hercules', 'Tigra', 'Mockingbird', 'Wasp'
  ],
  'Spider-Verse': [
    'Spider-Man', 'Miles Morales', 'Ghost-Spider', 'Silk', 'Spider-Woman', 'Spider-Man 2099', 
    'Scarlet Spider', 'Kaine Parker', 'Symbiote Spider-Man', 'Cosmic Spider-Man', 'Black Cat'
  ],
  'X-Men': [
    'Wolverine', 'Cyclops', 'Jean Grey', 'Storm', 'Gambit', 'Rogue', 'Nightcrawler', 'Colossus', 
    'Beast', 'Iceman', 'Professor X', 'Emma Frost', 'Psylocke', 'Havok', 'Polaris', 'Jubilee', 
    'Bishop', 'Archangel', 'Shadowcat', 'Sunfire', 'Dazzler', 'Armor', 'Cannonball', 'Boom-Boom',
    'Forge', 'Banshee', 'Warpath', 'Longshot', 'Shatterstar', 'Magik', 'Cable', 'X-23', 'Old Man Logan'
  ],
  'Midnight Sons': [
    'Blade', 'Moon Knight', 'Morbius', 'Ghost Rider', 'Doctor Strange', 'Doctor Voodoo', 
    'Clea', 'Magik', 'Black Knight', 'Elsa Bloodstone', 'Werewolf by Night'
  ],
  'Black Order': [
    'Thanos', 'Cull Obsidian', 'Corvus Glaive', 'Proxima Midnight', 'Ebony Maw'
  ],
  'Guardians': [
    'Star-Lord', 'Gamora', 'Drax', 'Groot', 'Rocket Raccoon', 'Mantis', 'Nebula', 
    'Yondu', 'Cosmo', 'Adam Warlock'
  ],
  'Brotherhood': [
    'Magneto', 'Mystique', 'Sabretooth', 'Toad', 'Blob', 'Pyro', 'Avalanche', 
    'Mastermind', 'Destiny', 'Juggernaut'
  ],
  'Sinister Six': [
    'Green Goblin', 'Doctor Octopus', 'Venom', 'Carnage', 'Kraven', 'Mysterio', 
    'Sandman', 'Electro', 'Rhino', 'Vulture', 'Scorpion', 'Shocker', 'Lizard', 'Hobgoblin'
  ],
  'Defenders': [
    'Daredevil', 'Luke Cage', 'Iron Fist', 'Jessica Jones', 'The Punisher', 'Punisher', 
    'Elektra', 'Misty Knight', 'Colleen Wing', 'Echo', 'Bullseye'
  ],
  'Cosmic Entities': [
    'Knull', 'Galactus', 'Silver Surfer', 'Living Tribunal', 'Beyonder', 'Eternity', 
    'Phoenix Force', 'Odin', 'Celestials', 'Gorr', 'Surtur', 'The Void', 'Oblivion', 
    'Shuma-Gorath', 'King in Black Venom', 'Chthon', 'Cyttorak'
  ]
};

export function getCharacterFactions(characterName: string): Faction[] {
  const nameLower = characterName.toLowerCase();
  const matchedFactions: Faction[] = [];

  for (const [faction, members] of Object.entries(FACTION_MEMBERS) as [Faction, string[]][]) {
    if (members.some(m => nameLower.includes(m.toLowerCase()) || m.toLowerCase().includes(nameLower))) {
      matchedFactions.push(faction);
    }
  }

  return matchedFactions;
}

export function calculatePlayerSynergies(collection: Character[]): SynergyBonus[] {
  const factionCounts: Record<Faction, number> = {
    'Avengers': 0,
    'Spider-Verse': 0,
    'X-Men': 0,
    'Midnight Sons': 0,
    'Black Order': 0,
    'Guardians': 0,
    'Brotherhood': 0,
    'Sinister Six': 0,
    'Defenders': 0,
    'Cosmic Entities': 0,
  };

  collection.forEach(char => {
    const factions = getCharacterFactions(char.name);
    factions.forEach(f => {
      factionCounts[f] = (factionCounts[f] || 0) + 1;
    });
  });

  const activeSynergies: SynergyBonus[] = [];

  if (factionCounts['Avengers'] >= 2) {
    activeSynergies.push({
      faction: "Avengers",
      title: "Avengers Assemble!",
      count: factionCounts['Avengers'],
      bonusPower: 4,
      description: `+4 Combat Power to all Avengers (${factionCounts['Avengers']} fielded)`,
    });
  }

  if (factionCounts['Spider-Verse'] >= 2) {
    activeSynergies.push({
      faction: "Spider-Verse",
      title: "Spider-Verse Link",
      count: factionCounts['Spider-Verse'],
      bonusPower: 5,
      description: `+5 Agility & Evasion Power to all Web-Warriors (${factionCounts['Spider-Verse']} fielded)`,
    });
  }

  if (factionCounts['X-Men'] >= 2) {
    activeSynergies.push({
      faction: "X-Men",
      title: "X-Men Strike Force",
      count: factionCounts['X-Men'],
      bonusPower: 5,
      description: `+5 Critical Combat Power to all Mutants (${factionCounts['X-Men']} fielded)`,
    });
  }

  if (factionCounts['Midnight Sons'] >= 2) {
    activeSynergies.push({
      faction: "Midnight Sons",
      title: "Midnight Sons Dark Pact",
      count: factionCounts['Midnight Sons'],
      bonusPower: 5,
      description: `+5 Armor-Piercing Dark Magic Power (${factionCounts['Midnight Sons']} fielded)`,
    });
  }

  if (factionCounts['Black Order'] >= 2) {
    activeSynergies.push({
      faction: "Black Order",
      title: "Black Order Cosmic Terror",
      count: factionCounts['Black Order'],
      bonusPower: 6,
      description: `+6 Dominance Power for Thanos and his generals (${factionCounts['Black Order']} fielded)`,
    });
  }

  if (factionCounts['Guardians'] >= 2) {
    activeSynergies.push({
      faction: "Guardians",
      title: "Guardians of the Galaxy",
      count: factionCounts['Guardians'],
      bonusPower: 4,
      description: `+4 Outlaw Synergy Power (${factionCounts['Guardians']} fielded)`,
    });
  }

  if (factionCounts['Sinister Six'] >= 2) {
    activeSynergies.push({
      faction: "Sinister Six",
      title: "Sinister Syndicate",
      count: factionCounts['Sinister Six'],
      bonusPower: 5,
      description: `+5 Villainous Chaos Strike Power (${factionCounts['Sinister Six']} fielded)`,
    });
  }

  if (factionCounts['Defenders'] >= 2) {
    activeSynergies.push({
      faction: "Defenders",
      title: "Defenders of the Street",
      count: factionCounts['Defenders'],
      bonusPower: 4,
      description: `+4 Unbreakable Willpower (${factionCounts['Defenders']} fielded)`,
    });
  }

  if (factionCounts['Cosmic Entities'] >= 2) {
    activeSynergies.push({
      faction: "Cosmic Entities",
      title: "Cosmic Pantheon",
      count: factionCounts['Cosmic Entities'],
      bonusPower: 6,
      description: `+6 Universal Reality-Warping Power (${factionCounts['Cosmic Entities']} fielded)`,
    });
  }

  return activeSynergies;
}

export function getSynergyBonusForCharacter(character: Character, synergies: SynergyBonus[]): number {
  let totalBonus = 0;
  const factions = getCharacterFactions(character.name);

  synergies.forEach(syn => {
    if (factions.includes(syn.faction)) {
      totalBonus += syn.bonusPower;
    }
  });

  return totalBonus;
}

// 80 Iconic Marvel Tag-Team Dual Combos Engine (Original 12 + 68 New Combos)
export interface TagTeamCombo {
  id: string;
  hero1Name: string;
  hero2Name: string;
  comboTitle: string;
  comboDescription: string;
  bonusDualDamage: number;
  bannerColor: string;
  auraType: 'cosmic' | 'lightning' | 'gamma' | 'chaos' | 'symbiote' | 'fire';
}

export const TAG_TEAM_COMBOS: TagTeamCombo[] = [
  // 1. Classic Trinity & Original 12
  {
    id: "combo-avengers-trinity",
    hero1Name: "Iron Man",
    hero2Name: "Captain America",
    comboTitle: "AVENGERS ASSEMBLE: SHIELD REPULSOR OVERLOAD",
    comboDescription: "Iron Man fires maximum unibeams directly off Captain America's Vibranium Shield, creating a 360-degree refracted energy super-blast!",
    bonusDualDamage: 22,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-weapon-x",
    hero1Name: "Wolverine",
    hero2Name: "Deadpool",
    comboTitle: "WEAPON X: MAXIMUM BERSERKER BARRAGE",
    comboDescription: "Wolverine and Deadpool unleash an unstoppable whirlwind of dual adamantium katanas and claws with dual healing factors!",
    bonusDualDamage: 24,
    bannerColor: "#E11D48",
    auraType: "chaos",
  },
  {
    id: "combo-asgardian-gods",
    hero1Name: "Thor",
    hero2Name: "Loki",
    comboTitle: "ASGARDIAN THUNDER & ILLUSION GOD-STRIKE",
    comboDescription: "Loki confuses the foe with 10 mirrored illusions while Thor drops a catastrophic Mjolnir lightning bolt from above!",
    bonusDualDamage: 22,
    bannerColor: "#0284C7",
    auraType: "lightning",
  },
  {
    id: "combo-lethal-protectors",
    hero1Name: "Spider-Man",
    hero2Name: "Venom",
    comboTitle: "MAXIMUM CARNAGE: SYMBIOTE WEB LAUNCH",
    comboDescription: "Venom catapults Spider-Man wrapped in dense symbiote webbing for a supersonic concussive dropkick!",
    bonusDualDamage: 20,
    bannerColor: "#334155",
    auraType: "symbiote",
  },
  {
    id: "combo-chaos-mystics",
    hero1Name: "Doctor Strange",
    hero2Name: "Scarlet Witch",
    comboTitle: "CHAOS MYSTIC REALITY TEAR",
    comboDescription: "Doctor Strange opens the Mirror Dimension while Wanda floods it with raw Chaos Magic, warping space-time to crush the target!",
    bonusDualDamage: 26,
    bannerColor: "#7C3AED",
    auraType: "chaos",
  },
  {
    id: "combo-cosmic-annihilation",
    hero1Name: "Thanos",
    hero2Name: "Knull",
    comboTitle: "COSMIC MULTIVERSE OBLIVION",
    comboDescription: "The Mad Titan channels the Infinity Gauntlet alongside the All-Black Necrosword, severing the fabric of existence!",
    bonusDualDamage: 30,
    bannerColor: "#881337",
    auraType: "cosmic",
  },
  {
    id: "combo-gamma-titans",
    hero1Name: "Hulk",
    hero2Name: "She-Hulk",
    comboTitle: "GAMMA WORLD-BREAKER EARTHQUAKE",
    comboDescription: "Bruce and Jennifer smash the tectonic plates simultaneously, triggering a Richter-10 gamma shockwave across the arena!",
    bonusDualDamage: 24,
    bannerColor: "#15803D",
    auraType: "gamma",
  },
  {
    id: "combo-mutant-genesis",
    hero1Name: "Magneto",
    hero2Name: "Professor X",
    comboTitle: "MUTANT GENESIS: PSY-MAGNETIC PULSE",
    comboDescription: "Charles paralyzes the opponent's mind while Magneto collapses dense magnetic iron filings into a crushing singularity!",
    bonusDualDamage: 25,
    bannerColor: "#9333EA",
    auraType: "chaos",
  },
  {
    id: "combo-guardians-blaster",
    hero1Name: "Star-Lord",
    hero2Name: "Rocket Raccoon",
    comboTitle: "HADRON ENFORCER MOON-SHATTER CANNON",
    comboDescription: "Rocket mounts Peter's shoulders wielding a customized Hadron Enforcer particle cannon with double plasma yield!",
    bonusDualDamage: 21,
    bannerColor: "#EA580C",
    auraType: "cosmic",
  },
  {
    id: "combo-hells-kitchen",
    hero1Name: "Daredevil",
    hero2Name: "The Punisher",
    comboTitle: "HELL'S KITCHEN SUPREME RETRIBUTION",
    comboDescription: "Daredevil disarms the enemy at close quarters while Frank Castle unloads high-caliber armor-piercing artillery!",
    bonusDualDamage: 18,
    bannerColor: "#991B1B",
    auraType: "fire",
  },
  {
    id: "combo-wakandan-royalty",
    hero1Name: "Black Panther",
    hero2Name: "Storm",
    comboTitle: "WAKANDAN ROYAL TEMPEST",
    comboDescription: "Ororo calls down hurricane gale winds while T'Challa detonates an overcharged kinetic vibranium energy pulse!",
    bonusDualDamage: 23,
    bannerColor: "#6366F1",
    auraType: "lightning",
  },
  {
    id: "combo-midnight-knights",
    hero1Name: "Ghost Rider",
    hero2Name: "Blade",
    comboTitle: "DAMNATION HELLFIRE BLADE",
    comboDescription: "Ghost Rider ignites Blade's titanium broadsword with eternal Hellfire, delivering an unholy soul-scorching slice!",
    bonusDualDamage: 22,
    bannerColor: "#F97316",
    auraType: "fire",
  },

  // 2. Spider-Verse & Web-Warriors (Combos 13-20)
  {
    id: "combo-spider-generations",
    hero1Name: "Spider-Man",
    hero2Name: "Miles Morales",
    comboTitle: "BROOKLYN VENOM-WEB THWIP-STRIKE",
    comboDescription: "Peter wraps the target in high-tensile impact webbing while Miles channels a 50,000-volt bio-electric Venom Blast!",
    bonusDualDamage: 23,
    bannerColor: "#EF4444",
    auraType: "lightning",
  },
  {
    id: "combo-ghost-silk",
    hero1Name: "Ghost-Spider",
    hero2Name: "Silk",
    comboTitle: "MULTIVERSE DRUMBEAT SILK ENTANGLEMENT",
    comboDescription: "Gwen executes acrobatic aerial kicks while Cindy Moon spins organic barbed silk ribbons binding the target immobilized!",
    bonusDualDamage: 20,
    bannerColor: "#EC4899",
    auraType: "symbiote",
  },
  {
    id: "combo-spider-2099",
    hero1Name: "Spider-Man 2099",
    hero2Name: "Spider-Man",
    comboTitle: "CHRONO-TALON MULTIVERSE SLAM",
    comboDescription: "Miguel O'Hara dives with futuristic solid-light antigravity claws while Peter swings in for a devastating double-heel drop!",
    bonusDualDamage: 22,
    bannerColor: "#1E40AF",
    auraType: "cosmic",
  },
  {
    id: "combo-black-cat-spidey",
    hero1Name: "Spider-Man",
    hero2Name: "Black Cat",
    comboTitle: "BAD LUCK CAT BURGLAR DIVE",
    comboDescription: "Felicia hexes the target with bad-luck probability shifts right as Peter delivers a blinding swing-kick!",
    bonusDualDamage: 19,
    bannerColor: "#475569",
    auraType: "chaos",
  },
  {
    id: "combo-scarlet-spiders",
    hero1Name: "Scarlet Spider",
    hero2Name: "Kaine Parker",
    comboTitle: "CLONE CONSPIRACY: STINGER IMPALEMENT",
    comboDescription: "Ben Reilly blinds with impact web clusters while Kaine pops razor-sharp arm bone stingers for brutal piercing damage!",
    bonusDualDamage: 21,
    bannerColor: "#B91C1C",
    auraType: "fire",
  },
  {
    id: "combo-maximum-symbiosis",
    hero1Name: "Venom",
    hero2Name: "Carnage",
    comboTitle: "ABSOLUTE CARNAGE: RED & BLACK SANGUINE MAELSTROM",
    comboDescription: "Venom and Carnage merge their tendrils into an apocalyptic blood-axe tsunami slashing through all shields!",
    bonusDualDamage: 26,
    bannerColor: "#991B1B",
    auraType: "symbiote",
  },
  {
    id: "combo-symbiote-king",
    hero1Name: "King in Black Venom",
    hero2Name: "Knull",
    comboTitle: "NECRO-VOID APOCALYPSE BLADE",
    comboDescription: "The Symbiote God and Eddie Brock summon a billion necro-tendrils blotting out the sun and eviscerating the target!",
    bonusDualDamage: 32,
    bannerColor: "#0F172A",
    auraType: "symbiote",
  },
  {
    id: "combo-spider-woman-captain-marvel",
    hero1Name: "Spider-Woman",
    hero2Name: "Captain Marvel",
    comboTitle: "VENOM BLAST BINARY BOMBARDMENT",
    comboDescription: "Jessica Drew shocks with bio-electric venom blasts while Carol Danvers descends in blazing Binary cosmic fury!",
    bonusDualDamage: 24,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },

  // 3. X-Men & Mutant Powerhouses (Combos 21-35)
  {
    id: "combo-fastball-special",
    hero1Name: "Colossus",
    hero2Name: "Wolverine",
    comboTitle: "CLASSIC FASTBALL SPECIAL!",
    comboDescription: "Colossus hurls Wolverine at Mach-2 speeds with fully unsheathed adamantium claws slicing through armored titans!",
    bonusDualDamage: 25,
    bannerColor: "#B45309",
    auraType: "gamma",
  },
  {
    id: "combo-cyclops-jean",
    hero1Name: "Cyclops",
    hero2Name: "Jean Grey",
    comboTitle: "TELEPATHIC OPTIC MEGABLAST",
    comboDescription: "Jean guides Scott's uninhibited dimensional Optic Blast with telekinetic precision directly to vital pressure points!",
    bonusDualDamage: 24,
    bannerColor: "#DC2626",
    auraType: "chaos",
  },
  {
    id: "combo-gambit-rogue",
    hero1Name: "Gambit",
    hero2Name: "Rogue",
    comboTitle: "KINETIC SOUTHERN BELLE DETONATION",
    comboDescription: "Remy supercharges Rogue's bare fist with pure kinetic explosive energy as she lands a supersonic haymaker!",
    bonusDualDamage: 23,
    bannerColor: "#16A34A",
    auraType: "lightning",
  },
  {
    id: "combo-nightcrawler-colossus",
    hero1Name: "Nightcrawler",
    hero2Name: "Colossus",
    comboTitle: "BAMF! TITANIUM METEOR DROP",
    comboDescription: "Kurt teleports Colossus 5,000 feet into the upper atmosphere, dropping a 500-ton organic steel missile onto the foe!",
    bonusDualDamage: 22,
    bannerColor: "#4338CA",
    auraType: "chaos",
  },
  {
    id: "combo-cable-deadpool",
    hero1Name: "Cable",
    hero2Name: "Deadpool",
    comboTitle: "CHRONO-ARMED MERCENARY MASSACRE",
    comboDescription: "Nathan Summers locks the target in a temporal telekinetic stasis field while Wade empties every rocket and magazine!",
    bonusDualDamage: 23,
    bannerColor: "#D97706",
    auraType: "fire",
  },
  {
    id: "combo-iceman-firestar",
    hero1Name: "Iceman",
    hero2Name: "Sunfire",
    comboTitle: "THERMAL SHOCKWAVE: ABSOLUTE ZERO & SOLAR FLARE",
    comboDescription: "Bobby Drake flashes freezes the target to 0 Kelvin before Sunfire detonates atomic solar plasma, fracturing armor instantly!",
    bonusDualDamage: 25,
    bannerColor: "#06B6D4",
    auraType: "fire",
  },
  {
    id: "combo-magik-colossus",
    hero1Name: "Magik",
    hero2Name: "Colossus",
    comboTitle: "RASPUTIN LIMBO SOULSWORD STRIKE",
    comboDescription: "Illyana teleports her brother through the demonic realm of Limbo, empowering his steel fists with raw eldritch Soulsword magic!",
    bonusDualDamage: 24,
    bannerColor: "#9333EA",
    auraType: "chaos",
  },
  {
    id: "combo-psylocke-wolverine",
    hero1Name: "Psylocke",
    hero2Name: "Wolverine",
    comboTitle: "PSYCHIC ADAMANTIUM CEREBRAL FLURRY",
    comboDescription: "Betsy pierces the mind with a glowing psychic katana while Logan eviscerates the physical shell with adamantium slashes!",
    bonusDualDamage: 23,
    bannerColor: "#A855F7",
    auraType: "chaos",
  },
  {
    id: "combo-bishop-cable",
    hero1Name: "Bishop",
    hero2Name: "Cable",
    comboTitle: "TIME-DISPLACED PLASMA ONSLAUGHT",
    comboDescription: "Bishop absorbs incoming kinetic blast energy to overload Cable's futuristic heavy plasma artillery cannon!",
    bonusDualDamage: 22,
    bannerColor: "#2563EB",
    auraType: "lightning",
  },
  {
    id: "combo-phoenix-jean",
    hero1Name: "Jean Grey",
    hero2Name: "Phoenix Force",
    comboTitle: "COSMIC RENAISSANCE: PHOENIX FIRE CLEAVE",
    comboDescription: "The cosmic entity of life and destruction immolates the entire arena in white-hot psychic flame, disintegrating matter!",
    bonusDualDamage: 32,
    bannerColor: "#F97316",
    auraType: "fire",
  },
  {
    id: "combo-magneto-mystique",
    hero1Name: "Magneto",
    hero2Name: "Mystique",
    comboTitle: "BROTHERHOOD SHAPE-SHIFTING AMBUSH",
    comboDescription: "Raven infiltrates the enemy blind spot to plant magnetic metallic beacons, allowing Magneto to crush the target with railgun velocity!",
    bonusDualDamage: 22,
    bannerColor: "#6B21A8",
    auraType: "chaos",
  },
  {
    id: "combo-emma-frost-cyclops",
    hero1Name: "Emma Frost",
    hero2Name: "Cyclops",
    comboTitle: "DIAMOND REFRACTION OPTIC CANNON",
    comboDescription: "Scott fires a full-power Optic Blast into Emma's flawless organic diamond form, scattering hundreds of lethal focused laser beams!",
    bonusDualDamage: 24,
    bannerColor: "#E2E8F0",
    auraType: "lightning",
  },
  {
    id: "combo-x23-wolverine",
    hero1Name: "X-23",
    hero2Name: "Wolverine",
    comboTitle: "HEREDITARY ODYSSEY ADAMANTIUM WHIRLWIND",
    comboDescription: "Logan and Laura attack in tandem with arm and foot talons, creating an inescapable cross-slash blender of slicing metal!",
    bonusDualDamage: 23,
    bannerColor: "#E11D48",
    auraType: "chaos",
  },
  {
    id: "combo-juggernaut-blob",
    hero1Name: "Juggernaut",
    hero2Name: "Blob",
    comboTitle: "UNSTOPPABLE GRAVITATIONAL CRUSH",
    comboDescription: "Blob roots the foe in an immovable gravitational anchor while the Cyttorak-empowered Juggernaut charges like a freight train!",
    bonusDualDamage: 23,
    bannerColor: "#78350F",
    auraType: "gamma",
  },
  {
    id: "combo-apocalypse-archangel",
    hero1Name: "Apocalypse",
    hero2Name: "Archangel",
    comboTitle: "HORSEMEN OF DEATH TECHNO-ORGANIC RAIN",
    comboDescription: "En Sabah Nur enhances Warren's metallic razor-wings, firing a million poisonous razor-fletchettes from high orbit!",
    bonusDualDamage: 26,
    bannerColor: "#3B82F6",
    auraType: "chaos",
  },

  // 4. Avengers & Earth's Mightiest Heroes (Combos 36-50)
  {
    id: "combo-thunder-and-metal",
    hero1Name: "Iron Man",
    hero2Name: "Thor",
    comboTitle: "MJOLNIR LIGHTNING OVERCHARGED REPULSORS",
    comboDescription: "Thor channels 1.21 Gigawatts of lightning straight into Tony Stark's Arc Reactor, unleashing a 400% overcharged chest beam!",
    bonusDualDamage: 25,
    bannerColor: "#0284C7",
    auraType: "lightning",
  },
  {
    id: "combo-cap-thor",
    hero1Name: "Captain America",
    hero2Name: "Thor",
    comboTitle: "WORTHY VIBRANIUM THUNDERCLAP",
    comboDescription: "Cap hurls his shield as Thor strikes it mid-flight with Mjolnir, projecting a sonic thunder shockwave flattening the arena!",
    bonusDualDamage: 24,
    bannerColor: "#3B82F6",
    auraType: "lightning",
  },
  {
    id: "combo-hulk-wolverine",
    hero1Name: "Hulk",
    hero2Name: "Wolverine",
    comboTitle: "GAMMA RAGE & ADAMANTIUM RUPTURE",
    comboDescription: "Hulk batters the enemy into paste while Logan dives in from above to drive his claws through the ruptured armor!",
    bonusDualDamage: 25,
    bannerColor: "#16A34A",
    auraType: "gamma",
  },
  {
    id: "combo-iron-man-war-machine",
    hero1Name: "Iron Man",
    hero2Name: "War Machine",
    comboTitle: "FULL SALVO: BUNKER BUSTER BARRAGE",
    comboDescription: "Tony and Rhodey lock targeting systems to unload micro-missiles, smart-mines, shoulder miniguns, and dual unibeams!",
    bonusDualDamage: 23,
    bannerColor: "#64748B",
    auraType: "fire",
  },
  {
    id: "combo-cap-bucky",
    hero1Name: "Captain America",
    hero2Name: "Winter Soldier",
    comboTitle: "HOWLING COMMANDOS CYBERNETIC CROSSFIRE",
    comboDescription: "Steve and Bucky pass the Vibranium Shield between seamless boxing combinations and high-impact bionic arm punches!",
    bonusDualDamage: 21,
    bannerColor: "#1E3A8A",
    auraType: "lightning",
  },
  {
    id: "combo-falcon-winter-soldier",
    hero1Name: "Falcon",
    hero2Name: "Winter Soldier",
    comboTitle: "AERIAL REDWING & BIONIC OVERRIDE",
    comboDescription: "Sam swoops in with vibranium wings and Redwing drones to stagger the foe for Bucky's crushing bionic haymaker!",
    bonusDualDamage: 20,
    bannerColor: "#DC2626",
    auraType: "fire",
  },
  {
    id: "combo-vision-wanda",
    hero1Name: "Vision",
    hero2Name: "Scarlet Witch",
    comboTitle: "SOLAR GEM & CHAOS REALITY TEAR",
    comboDescription: "Vision increases mass to diamond density while firing the Solar Mind Gem alongside Wanda's reality-altering hex rifts!",
    bonusDualDamage: 26,
    bannerColor: "#E11D48",
    auraType: "chaos",
  },
  {
    id: "combo-antman-wasp",
    hero1Name: "Ant-Man",
    hero2Name: "Wasp",
    comboTitle: "PYM PARTICLE QUANTUM STINGER STORM",
    comboDescription: "Scott grows into Giant-Man to swat down the enemy while Janet shrinks to subatomic scale firing stinging bio-lasers from within!",
    bonusDualDamage: 22,
    bannerColor: "#CA8A04",
    auraType: "cosmic",
  },
  {
    id: "combo-hawkeye-black-widow",
    hero1Name: "Hawkeye",
    hero2Name: "Black Widow",
    comboTitle: "BUDAPEST TACTICAL TRICK-ARROW AMBUSH",
    comboDescription: "Natasha restrains the enemy with electric Widow's Bite cables while Clint fires a thermite vibranium trick-arrow into the heart!",
    bonusDualDamage: 19,
    bannerColor: "#111827",
    auraType: "lightning",
  },
  {
    id: "combo-thor-beta-ray-bill",
    hero1Name: "Thor",
    hero2Name: "Beta Ray Bill",
    comboTitle: "MJOLNIR & STORMBREAKER TWIN GALAXY STORM",
    comboDescription: "The two worthy warriors clash Mjolnir and Stormbreaker together, calling down an all-father cosmic tempest shattering planets!",
    bonusDualDamage: 27,
    bannerColor: "#0284C7",
    auraType: "lightning",
  },
  {
    id: "combo-shang-chi-iron-fist",
    hero1Name: "Shang-Chi",
    hero2Name: "Iron Fist",
    comboTitle: "TEN RINGS & SHOU-LAO DRAGON FIST",
    comboDescription: "Shang-Chi commands the mythical Ten Rings to corral the enemy into Danny Rand's blazing chi-infused dragon fist!",
    bonusDualDamage: 24,
    bannerColor: "#EAB308",
    auraType: "fire",
  },
  {
    id: "combo-scarlet-quicksilver",
    hero1Name: "Scarlet Witch",
    hero2Name: "Quicksilver",
    comboTitle: "MAXIMOFF TWIN SUPERSONIC HEX CYCLONE",
    comboDescription: "Pietro runs at Mach-10 creating a vacuum vortex while Wanda fills the center with crushing chaos hex spheres!",
    bonusDualDamage: 24,
    bannerColor: "#84CC16",
    auraType: "chaos",
  },
  {
    id: "combo-black-widow-yelena",
    hero1Name: "Black Widow",
    hero2Name: "Yelena Belova",
    comboTitle: "RED ROOM SISTERHOOD EXCLUSION",
    comboDescription: "Natasha and Yelena perform flawless synchronized acrobatic takedowns, detonating dual electro-shock stun batons!",
    bonusDualDamage: 20,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-hercules-thor",
    hero1Name: "Hercules",
    hero2Name: "Thor",
    comboTitle: "GODS OF OLYMPUS & ASGARD BATTLE CRY",
    comboDescription: "The Prince of Power and God of Thunder deliver a dual god-strength uppercut launching the titan into the stratosphere!",
    bonusDualDamage: 25,
    bannerColor: "#F59E0B",
    auraType: "lightning",
  },
  {
    id: "combo-captain-marvel-ms-marvel",
    hero1Name: "Captain Marvel",
    hero2Name: "Ms. Marvel",
    comboTitle: "BINARY EMBIGGENED HARD-LIGHT PUNCH",
    comboDescription: "Kamala enlarges her fist with crystalline hard-light armor as Carol charges it with raw Binary cosmic photon energy!",
    bonusDualDamage: 23,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },

  // 5. Fantastic Four & Cosmic Entities (Combos 51-65)
  {
    id: "combo-fantastic-duo",
    hero1Name: "Mister Fantastic",
    hero2Name: "Invisible Woman",
    comboTitle: "FORCEFIELD COMPRESSION & ELASTIC SLINGSHOT",
    comboDescription: "Sue Storm encases the foe in an unbreakable microscopic forcefield while Reed wraps around to catapult a supersonic slam!",
    bonusDualDamage: 24,
    bannerColor: "#2563EB",
    auraType: "cosmic",
  },
  {
    id: "combo-torch-thing",
    hero1Name: "Human Torch",
    hero2Name: "The Thing",
    comboTitle: "SUPERNOVA CLOBBERIN' TIME!",
    comboDescription: "Johnny Storm unleashes Nova-level heat to superheat the target before Ben Grimm delivers a shattering haymaker punch!",
    bonusDualDamage: 23,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-silver-surfer-galactus",
    hero1Name: "Silver Surfer",
    hero2Name: "Galactus",
    comboTitle: "HERALD OF THE END: POWER COSMIC CATACLYSM",
    comboDescription: "Norrin Radd opens a cosmic cosmic conduit while Galactus siphons the lifeforce of entire star systems to annihilate the foe!",
    bonusDualDamage: 34,
    bannerColor: "#9333EA",
    auraType: "cosmic",
  },
  {
    id: "combo-warlock-thanos",
    hero1Name: "Adam Warlock",
    hero2Name: "Thanos",
    comboTitle: "INFINITY WATCH: SOUL GEM & TIME REVERSAL",
    comboDescription: "Adam traps the enemy's soul in the Soul World while Thanos freezes their physical matter in endless temporal loops!",
    bonusDualDamage: 28,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-nova-surfer",
    hero1Name: "Nova",
    hero2Name: "Silver Surfer",
    comboTitle: "NOVA CORPS & POWER COSMIC CONVERGENCE",
    comboDescription: "Richard Rider channels the entire Xandarian Worldmind into Silver Surfer's board for a lightspeed galaxy-cleaving strike!",
    bonusDualDamage: 26,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
  {
    id: "combo-groot-rocket",
    hero1Name: "Groot",
    hero2Name: "Rocket Raccoon",
    comboTitle: "WE ARE GROOT: ROTARY CANNON ROOT TRAP",
    comboDescription: "Groot roots the enemy in unbreakable wooden tendrils while Rocket rides his head firing micro-missile Gatling cannons!",
    bonusDualDamage: 22,
    bannerColor: "#15803D",
    auraType: "gamma",
  },
  {
    id: "combo-gamora-nebula",
    hero1Name: "Gamora",
    hero2Name: "Nebula",
    comboTitle: "DAUGHTERS OF THANOS GODSLAYER BLADES",
    comboDescription: "Gamora executes lethal acrobatic Godslayer sword strikes while Nebula unleashes overcharged cybernetic energy blasters!",
    bonusDualDamage: 22,
    bannerColor: "#059669",
    auraType: "cosmic",
  },
  {
    id: "combo-drax-mantis",
    hero1Name: "Drax",
    hero2Name: "Mantis",
    comboTitle: "EMPATHIC SLEEP & DESTROYER DUAL BLADES",
    comboDescription: "Mantis touches the target's forehead forcing instant catatonic sleep as Drax drives dual daggers deep into their chest!",
    bonusDualDamage: 21,
    bannerColor: "#10B981",
    auraType: "chaos",
  },
  {
    id: "combo-thanos-ebony-maw",
    hero1Name: "Thanos",
    hero2Name: "Ebony Maw",
    comboTitle: "BLACK ORDER PSYCHIC DECONSTRUCTION",
    comboDescription: "Ebony Maw lifts thousands of razor-sharp stone shards telekinetically while Thanos pulverizes the target with the Power Stone!",
    bonusDualDamage: 27,
    bannerColor: "#475569",
    auraType: "cosmic",
  },
  {
    id: "combo-gorr-knull",
    hero1Name: "Gorr",
    hero2Name: "Knull",
    comboTitle: "ALL-BLACK GOD-SLAYER ECLIPSE",
    comboDescription: "The God Butcher and the Void King summon a primordial black hole that slaughters gods and tears through all dimensions!",
    bonusDualDamage: 32,
    bannerColor: "#020617",
    auraType: "symbiote",
  },
  {
    id: "combo-sentry-void",
    hero1Name: "Sentry",
    hero2Name: "The Void",
    comboTitle: "ONE MILLION EXPLODING SUNS & VOID SHADOWS",
    comboDescription: "Robert Reynolds channels the blinding power of a million exploding suns while the Void tears the target apart from inside!",
    bonusDualDamage: 32,
    bannerColor: "#FACC15",
    auraType: "cosmic",
  },
  {
    id: "combo-black-bolt-medusa",
    hero1Name: "Black Bolt",
    hero2Name: "Medusa",
    comboTitle: "INHUMAN ROYAL SCREAM & LIVING TENDRILS",
    comboDescription: "Medusa restrains the target with steel-hard tensile red hair while Black Bolt utters a quasi-sonic whisper leveling mountains!",
    bonusDualDamage: 28,
    bannerColor: "#6366F1",
    auraType: "lightning",
  },
  {
    id: "combo-namor-black-panther",
    hero1Name: "Namor",
    hero2Name: "Black Panther",
    comboTitle: "IMPERIUS REX & VIBRANIUM TRIDENT SURGE",
    comboDescription: "Namor summons a tidal wave of oceanic pressure while T'Challa detonates vibranium kinetic shock charges beneath the surface!",
    bonusDualDamage: 24,
    bannerColor: "#0D9488",
    auraType: "lightning",
  },
  {
    id: "combo-doom-kang",
    hero1Name: "Doctor Doom",
    hero2Name: "Kang the Conqueror",
    comboTitle: "CHRONO-SORCERY OMNIVERSE EXTINCTION",
    comboDescription: "Doom weaves dark Latverian sorcery while Kang summons armies from across 1,000 timelines to erase the target from history!",
    bonusDualDamage: 30,
    bannerColor: "#059669",
    auraType: "cosmic",
  },
  {
    id: "combo-infinity-ultron-thanos",
    hero1Name: "Infinity Ultron",
    hero2Name: "Thanos",
    comboTitle: "TWELVE INFINITY STONES MULTIVERSAL CLEAVE",
    comboDescription: "The two ultimate conquerors unite twelve Infinity Stones, eradicating the target across all parallel realities simultaneously!",
    bonusDualDamage: 34,
    bannerColor: "#06B6D4",
    auraType: "cosmic",
  },

  // 6. Midnight Sons & Street Level Champions (Combos 66-80)
  {
    id: "combo-heroes-for-hire",
    hero1Name: "Luke Cage",
    hero2Name: "Iron Fist",
    comboTitle: "HEROES FOR HIRE: UNBREAKABLE DRAGON IMPACT",
    comboDescription: "Luke Cage absorbs the brunt of all attacks with impenetrable skin while Danny Rand unleashes the blazing Iron Fist through his back!",
    bonusDualDamage: 22,
    bannerColor: "#EAB308",
    auraType: "fire",
  },
  {
    id: "combo-jessica-luke",
    hero1Name: "Jessica Jones",
    hero2Name: "Luke Cage",
    comboTitle: "HARLEM & HELL'S KITCHEN SEISMIC SLAM",
    comboDescription: "Jessica lifts the target 50 feet into the air and powerbombs them into Luke Cage's titanium-solid waiting uppercut!",
    bonusDualDamage: 21,
    bannerColor: "#334155",
    auraType: "gamma",
  },
  {
    id: "combo-moon-knight-blade",
    hero1Name: "Moon Knight",
    hero2Name: "Blade",
    comboTitle: "KHONSHU CRESCENT & SILVER VAMPIRE BANE",
    comboDescription: "Marc Spector hurls adamantium crescent darts into vital arteries as Blade slices through with silver-plated katana speed!",
    bonusDualDamage: 22,
    bannerColor: "#E2E8F0",
    auraType: "chaos",
  },
  {
    id: "combo-strange-clea",
    hero1Name: "Doctor Strange",
    hero2Name: "Clea",
    comboTitle: "DARK DIMENSION FLAMES OF THE FALTORINE",
    comboDescription: "Strange and Clea combine the Eye of Agamotto with Dark Dimension royal flames, incinerating mystical defenses!",
    bonusDualDamage: 25,
    bannerColor: "#A855F7",
    auraType: "chaos",
  },
  {
    id: "combo-strange-wong",
    hero1Name: "Doctor Strange",
    hero2Name: "Wong",
    comboTitle: "KAMAR-TAJ ELDRITCH SLING-RING TRAP",
    comboDescription: "Wong opens twin sling-ring portals looping the opponent's own attacks back at them as Strange unleashes the Vishanti!",
    bonusDualDamage: 22,
    bannerColor: "#D97706",
    auraType: "chaos",
  },
  {
    id: "combo-morbius-blade",
    hero1Name: "Morbius",
    hero2Name: "Blade",
    comboTitle: "MIDNIGHT BLOODLINE SANGUINE ASSAULT",
    comboDescription: "The Living Vampire paralyzes the foe with hypersonic screams while the Daywalker delivers an executioner decaptitation slice!",
    bonusDualDamage: 21,
    bannerColor: "#881337",
    auraType: "symbiote",
  },
  {
    id: "combo-she-hulk-daredevil",
    hero1Name: "She-Hulk",
    hero2Name: "Daredevil",
    comboTitle: "LEGAL JUSTICIARS: BILLIE CLUB SMASH",
    comboDescription: "Daredevil disorients the enemy with sonic ricocheting billy clubs while Jennifer Walters delivers a 100-ton gavel smash!",
    bonusDualDamage: 22,
    bannerColor: "#16A34A",
    auraType: "gamma",
  },
  {
    id: "combo-domino-deadpool",
    hero1Name: "Domino",
    hero2Name: "Deadpool",
    comboTitle: "PROBABILITY OVERLOAD: 100% HEADSHOT ACCURACY",
    comboDescription: "Domino bends the laws of probability so every wild ricochet from Deadpool's dual pistols lands as an impossible critical hit!",
    bonusDualDamage: 21,
    bannerColor: "#475569",
    auraType: "chaos",
  },
  {
    id: "combo-sabretooth-wolverine",
    hero1Name: "Sabretooth",
    hero2Name: "Wolverine",
    comboTitle: "FERAL RIVALRY BLOODLUST EXECUTION",
    comboDescription: "The ancient rivals put aside their blood feud for a split second, shredding the target into ribboned meat with dual feral pounces!",
    bonusDualDamage: 25,
    bannerColor: "#9A3412",
    auraType: "fire",
  },
  {
    id: "combo-punisher-ghost-rider",
    hero1Name: "The Punisher",
    hero2Name: "Ghost Rider",
    comboTitle: "HELLFIRE GATLING PENANCE STARE",
    comboDescription: "Frank Castle empties Hellfire-charged miniguns into the target before Johnny Blaze locks eyes for an agonizing Penance Stare!",
    bonusDualDamage: 26,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-cosmic-ghost-rider",
    hero1Name: "Cosmic Ghost Rider",
    hero2Name: "Thanos",
    comboTitle: "BABY THANOS TIMELINE PUNISHMENT",
    comboDescription: "The Cosmic Ghost Rider unleashes Power Cosmic Hellfire chains while the Mad Titan crushes the target with raw cosmic might!",
    bonusDualDamage: 30,
    bannerColor: "#F97316",
    auraType: "cosmic",
  },
  {
    id: "combo-doc-ock-goblin",
    hero1Name: "Doctor Octopus",
    hero2Name: "Green Goblin",
    comboTitle: "SINISTER MASTERMINDS: PUMPKIN TENTACLE CRUSH",
    comboDescription: "Otto binds the target with titanium mechanical tentacles while Norman flies in on the Goblin Glider dropping a cluster of Pumpkin Bombs!",
    bonusDualDamage: 24,
    bannerColor: "#16A34A",
    auraType: "fire",
  },
  {
    id: "combo-moon-knight-mr-knight",
    hero1Name: "Moon Knight",
    hero2Name: "Mr. Knight",
    comboTitle: "FISTS OF KHONSHU DUAL PERSONALITY BLUDGEON",
    comboDescription: "Marc Spector and Steven Grant strike in synchronized martial arts harmony, channeling the ancient wrath of the Egyptian Moon God!",
    bonusDualDamage: 22,
    bannerColor: "#F8FAFC",
    auraType: "chaos",
  },
  {
    id: "combo-captain-marvel-spectrum",
    hero1Name: "Captain Marvel",
    hero2Name: "Spectrum",
    comboTitle: "ELECTROMAGNETIC PHOTON SUPERNOVA",
    comboDescription: "Monica Rambeau transforms into pure gamma-wave radiation as Carol Danvers magnifies her output into a blinding solar beam!",
    bonusDualDamage: 25,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
  {
    id: "combo-daredevil-elektra",
    hero1Name: "Daredevil",
    hero2Name: "Elektra",
    comboTitle: "THE HAND'S DEMISE: DUAL SAI EXECUTION",
    comboDescription: "Elektra drives twin razor sais through vulnerable pressure points while Daredevil lands a shattering blind acrobat kick!",
    bonusDualDamage: 21,
    bannerColor: "#B91C1C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-100",
    hero1Name: "Spider-Man",
    hero2Name: "Miles Morales",
    comboTitle: "SPIDER-VERSE CONVERGENCE: DUAL THWIP BURST",
    comboDescription: "Peter Parker webs up the foe while Miles delivers a venom-blast super punch!",
    bonusDualDamage: 23,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-101",
    hero1Name: "Spider-Gwen",
    hero2Name: "Miles Morales",
    comboTitle: "DIMENSIONAL DRUM SOLO: GRAVITY KICK",
    comboDescription: "Spider-Gwen pulls the enemy downward as Miles hits a bio-electric lightning smash!",
    bonusDualDamage: 22,
    bannerColor: "#EC4899",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-102",
    hero1Name: "Spider-Man 2099",
    hero2Name: "Spider-Man",
    comboTitle: "MULTIVERSAL TIMELINE ENFORCEMENT",
    comboDescription: "Miguel O'Hara strikes with talons while Peter Parker creates a massive web-net barricade!",
    bonusDualDamage: 24,
    bannerColor: "#3B82F6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-103",
    hero1Name: "Silk",
    hero2Name: "Spider-Man",
    comboTitle: "ORGANIC SILK WEAPON STORM",
    comboDescription: "Silk binds the target with razor-sharp silk threads allowing a devastating aerial dropkick!",
    bonusDualDamage: 20,
    bannerColor: "#F43F5E",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-104",
    hero1Name: "Venom",
    hero2Name: "Carnage",
    comboTitle: "MAXIMUM SYMBIOTE MASSACRE",
    comboDescription: "Venom and Carnage combine their tendril mass into a chaotic storm of living spikes!",
    bonusDualDamage: 25,
    bannerColor: "#991B1B",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-105",
    hero1Name: "Anti-Venom",
    hero2Name: "Spider-Man",
    comboTitle: "CLEANSING CAUSTIC WEB IMPACT",
    comboDescription: "Anti-Venom purifies alien energies while Peter delivers a high-impact concussive smash!",
    bonusDualDamage: 22,
    bannerColor: "#FFFFFF",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-106",
    hero1Name: "Toxin",
    hero2Name: "Venom",
    comboTitle: "PRIMAL BROOD APEX ASSAULT",
    comboDescription: "Toxin and Venom envelop the battlefield in crushing symbiote tendril crushing power!",
    bonusDualDamage: 23,
    bannerColor: "#EA580C",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-107",
    hero1Name: "Spider-Man",
    hero2Name: "Black Cat",
    comboTitle: "FELINE AGILITY & WEB FLING",
    comboDescription: "Black Cat confuses the foe with bad luck while Spidey hurls them into orbit!",
    bonusDualDamage: 21,
    bannerColor: "#64748B",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-108",
    hero1Name: "Spider-Man",
    hero2Name: "Daredevil",
    comboTitle: "STREET LEVEL DEFENDERS BARRAGE",
    comboDescription: "Daredevil detects weak points and Spidey executes precision web-impact strikes!",
    bonusDualDamage: 21,
    bannerColor: "#EF4444",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-109",
    hero1Name: "Spider-Man",
    hero2Name: "Deadpool",
    comboTitle: "TEAM RED COMEDIC OVERKILL",
    comboDescription: "Deadpool causes absolute chaos while Spidey swings him like a human wrecking ball!",
    bonusDualDamage: 24,
    bannerColor: "#E11D48",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-110",
    hero1Name: "Iron Man",
    hero2Name: "War Machine",
    comboTitle: "HOUSE PARTY PROTOCOL: DOUBLE BARRAGE",
    comboDescription: "Tony and Rhodey unleash full micro-missile salvos and dual unibeams simultaneously!",
    bonusDualDamage: 24,
    bannerColor: "#B91C1C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-111",
    hero1Name: "Iron Man",
    hero2Name: "Rescue",
    comboTitle: "STARK TECH REPULSOR MATRIX",
    comboDescription: "Rescue shields Tony while both fire amplified photon blasters from synchronized drones!",
    bonusDualDamage: 23,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-112",
    hero1Name: "Iron Man",
    hero2Name: "Thor",
    comboTitle: "LIGHTNING-CHARGED UNIBEAM 400%",
    comboDescription: "Thor channels Mjolnir directly into Iron Man's arc reactor for a 400% power unibeam!",
    bonusDualDamage: 27,
    bannerColor: "#38BDF8",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-113",
    hero1Name: "Iron Man",
    hero2Name: "Hulk",
    comboTitle: "FASTBALL CODE GREEN EXPLOSION",
    comboDescription: "Iron Man boosts Hulk through the stratosphere for a kinetic meteor strike!",
    bonusDualDamage: 25,
    bannerColor: "#16A34A",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-114",
    hero1Name: "Iron Man",
    hero2Name: "Spider-Man",
    comboTitle: "IRON SPIDER PROTOCOL ENGAGED",
    comboDescription: "Tony activates orbital nanotech boosters on Peter's armor for supersonic strikes!",
    bonusDualDamage: 23,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-115",
    hero1Name: "Captain America",
    hero2Name: "Winter Soldier",
    comboTitle: "BROOKLYN BROS: SHIELD & METAL CLASH",
    comboDescription: "Cap throws the shield to Bucky who ricochets it with his vibranium cyber-arm!",
    bonusDualDamage: 24,
    bannerColor: "#2563EB",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-116",
    hero1Name: "Captain America",
    hero2Name: "Falcon",
    comboTitle: "REDWING AERIAL DROP PROTOCOL",
    comboDescription: "Sam Wilson provides high-speed aerial coverage as Steve lands a diving shield bash!",
    bonusDualDamage: 22,
    bannerColor: "#0284C7",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-117",
    hero1Name: "Captain America",
    hero2Name: "Black Panther",
    comboTitle: "VIBRANIUM ROYAL ALLIANCE",
    comboDescription: "Steve and T'Challa channel kinetic energy through twin vibranium suits into a shockwave!",
    bonusDualDamage: 25,
    bannerColor: "#8B5CF6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-118",
    hero1Name: "Thor",
    hero2Name: "Hulk",
    comboTitle: "REVENGERS: LIGHTNING SMASH",
    comboDescription: "Thor summons thunderous storms while Hulk slams the earth, splitting the arena in half!",
    bonusDualDamage: 26,
    bannerColor: "#15803D",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-119",
    hero1Name: "Thor",
    hero2Name: "Beta Ray Bill",
    comboTitle: "TWIN GOD-HAMMERS STORMBREAKER",
    comboDescription: "Mjolnir and Stormbreaker collide, releasing an apocalyptic solar thunderclap!",
    bonusDualDamage: 27,
    bannerColor: "#F59E0B",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-120",
    hero1Name: "Thor",
    hero2Name: "Mighty Thor (Jane Foster)",
    comboTitle: "LOVE & THUNDER GOD-STRIKE",
    comboDescription: "Jane Foster and Thor coordinate dual storm blasts, raining divine lightning from heaven!",
    bonusDualDamage: 26,
    bannerColor: "#F59E0B",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-121",
    hero1Name: "Thor",
    hero2Name: "Valkyrie",
    comboTitle: "VALKYRIE DRAGONFANG CAVALRY",
    comboDescription: "Valkyrie flies her pegasus through Thor's lightning storm for a decapitating plunge!",
    bonusDualDamage: 23,
    bannerColor: "#06B6D4",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-122",
    hero1Name: "Loki",
    hero2Name: "Sylvie",
    comboTitle: "GLORIOUS PURPOSE DUAL ENCHANTMENT",
    comboDescription: "Loki and Sylvie link hands, overwhelming the enemy's consciousness with multiversal magic!",
    bonusDualDamage: 25,
    bannerColor: "#10B981",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-123",
    hero1Name: "Doctor Strange",
    hero2Name: "Wong",
    comboTitle: "KAMAR-TAJ ELDTRITCH SLING-RING SLICER",
    comboDescription: "Wong and Strange open portal loops that redirect the foe's strongest attacks back at them!",
    bonusDualDamage: 23,
    bannerColor: "#F59E0B",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-124",
    hero1Name: "Doctor Strange",
    hero2Name: "Clea",
    comboTitle: "DARK DIMENSION SORCERY OVERDRIVE",
    comboDescription: "Clea summons flames of the Faltine while Strange weaves the Crimson Bands of Cyttorak!",
    bonusDualDamage: 26,
    bannerColor: "#A855F7",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-125",
    hero1Name: "Doctor Strange",
    hero2Name: "Doctor Voodoo",
    comboTitle: "VOODOO SPIRIT NECROMANCY REVERSAL",
    comboDescription: "Doctor Voodoo summons guardian loas while Strange binds the target in mystic chains!",
    bonusDualDamage: 24,
    bannerColor: "#9333EA",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-126",
    hero1Name: "Scarlet Witch",
    hero2Name: "Vision",
    comboTitle: "CHAOS REALITY & SOLAR DENSITY COLLAPSE",
    comboDescription: "Vision increases density to 500 tons while Wanda hex-warps probability around him!",
    bonusDualDamage: 26,
    bannerColor: "#E11D48",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-127",
    hero1Name: "Scarlet Witch",
    hero2Name: "Quicksilver",
    comboTitle: "MAXIMOFF TWINS SPEED-CHAOS BLITZ",
    comboDescription: "Pietro moves at Mach 10 to deliver Wanda's chaos hexes straight into the foe's heart!",
    bonusDualDamage: 25,
    bannerColor: "#DC2626",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-128",
    hero1Name: "Scarlet Witch",
    hero2Name: "Magneto",
    comboTitle: "HOUSE OF M GENETIC REALITY CRUSH",
    comboDescription: "Magneto controls iron in the blood while Wanda erases the enemy's defensive traits!",
    bonusDualDamage: 28,
    bannerColor: "#7C3AED",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-129",
    hero1Name: "Hulk",
    hero2Name: "She-Hulk",
    comboTitle: "GAMMA COUSINS SEISMIC PULVERIZE",
    comboDescription: "Jennifer Walters delivers a precision martial strike while Bruce delivers a world-breaking punch!",
    bonusDualDamage: 24,
    bannerColor: "#22C55E",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-130",
    hero1Name: "Hulk",
    hero2Name: "Red Hulk",
    comboTitle: "GAMMA & THERMAL EXPLOSION CRUCIBLE",
    comboDescription: "Red Hulk emits thermonuclear heat while Hulk unleashes unlimited kinetic rage!",
    bonusDualDamage: 26,
    bannerColor: "#EF4444",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-131",
    hero1Name: "Hulk",
    hero2Name: "Skaar",
    comboTitle: "SON OF HULK OLDPOWER CATACLYSM",
    comboDescription: "Skaar channels planetary tectonic plates while Hulk slams with tectonic might!",
    bonusDualDamage: 25,
    bannerColor: "#15803D",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-132",
    hero1Name: "Hawkeye",
    hero2Name: "Black Widow",
    comboTitle: "BUDAPEST SPECIAL: ARROW & STINGER BARRAGE",
    comboDescription: "Natasha draws enemy aggro with shock batons while Clint fires an anti-matter trick arrow!",
    bonusDualDamage: 23,
    bannerColor: "#7C3AED",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-133",
    hero1Name: "Hawkeye",
    hero2Name: "Kate Bishop",
    comboTitle: "TRICK ARROW HARMONIC MATRIX",
    comboDescription: "Clint and Kate fire 10 trick arrows simultaneously, creating sonic, ice, and explosive traps!",
    bonusDualDamage: 22,
    bannerColor: "#A855F7",
    auraType: "fire",
  },
  {
    id: "combo-expansion-134",
    hero1Name: "Black Widow",
    hero2Name: "Yelena Belova",
    comboTitle: "RED ROOM SISTERHOOD ASSAULT",
    comboDescription: "Yelena and Natasha execute flawless synchronized close-quarters combat execution!",
    bonusDualDamage: 22,
    bannerColor: "#EF4444",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-135",
    hero1Name: "Ant-Man",
    hero2Name: "Wasp",
    comboTitle: "PYM PARTICLE DISK SWARM CRUSH",
    comboDescription: "Wasp shrinks behind the foe with bio-stings as Giant-Man steps down with crushing force!",
    bonusDualDamage: 23,
    bannerColor: "#F59E0B",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-136",
    hero1Name: "Ant-Man",
    hero2Name: "Stature (Cassie Lang)",
    comboTitle: "DOUBLE GIANT-SIZE COLOSSAL SMASH",
    comboDescription: "Scott and Cassie grow to 60 feet tall for an earth-shattering dual foot stomp!",
    bonusDualDamage: 22,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-137",
    hero1Name: "Black Panther",
    hero2Name: "Shuri",
    comboTitle: "WAKANDAN GAUNTLET SONIC PULSE",
    comboDescription: "Shuri's panther vibranium gauntlets emit sonic blasts while T'Challa delivers a kinetic pounce!",
    bonusDualDamage: 24,
    bannerColor: "#8B5CF6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-138",
    hero1Name: "Black Panther",
    hero2Name: "Storm",
    comboTitle: "KING & QUEEN: VIBRANIUM LIGHTNING STORM",
    comboDescription: "Ororo calls down tempest category 5 lightning directly into T'Challa's kinetic shockwave suit!",
    bonusDualDamage: 27,
    bannerColor: "#6366F1",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-139",
    hero1Name: "Black Panther",
    hero2Name: "Okoye",
    comboTitle: "DORA MILAJE SPEAR & CLAW WALL",
    comboDescription: "Okoye throws her vibranium spear through the enemy as T'Challa slashes their defenses to pieces!",
    bonusDualDamage: 22,
    bannerColor: "#D97706",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-140",
    hero1Name: "Wolverine",
    hero2Name: "Colossus",
    comboTitle: "THE LEGENDARY FASTBALL SPECIAL",
    comboDescription: "Colossus hurls Wolverine at supersonic speed with unsheathed adamantium claws!",
    bonusDualDamage: 27,
    bannerColor: "#EAB308",
    auraType: "fire",
  },
  {
    id: "combo-expansion-141",
    hero1Name: "Wolverine",
    hero2Name: "X-23",
    comboTitle: "TALON CLAW DUAL SHREDDER",
    comboDescription: "Logan and Laura Kinney shred the enemy in a ruthless 6-claw flurry from both sides!",
    bonusDualDamage: 25,
    bannerColor: "#F43F5E",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-142",
    hero1Name: "Wolverine",
    hero2Name: "Sabretooth",
    comboTitle: "ANCIENT WEAPON X RIVAL CARNAGE",
    comboDescription: "Bitter enemies unite their feral instincts to rip the target to shreds!",
    bonusDualDamage: 25,
    bannerColor: "#D97706",
    auraType: "fire",
  },
  {
    id: "combo-expansion-143",
    hero1Name: "Cyclops",
    hero2Name: "Jean Grey",
    comboTitle: "PHOENIX TELEKINETIC OPTIC CANNON",
    comboDescription: "Jean guides Scott's full-power visor optic blast into a multi-directional psychic laser beam!",
    bonusDualDamage: 27,
    bannerColor: "#EF4444",
    auraType: "fire",
  },
  {
    id: "combo-expansion-144",
    hero1Name: "Cyclops",
    hero2Name: "Havok",
    comboTitle: "SUMMERS BROTHERS COSMIC PLASMA CONVERGENCE",
    comboDescription: "Scott's optic beam collides with Alex's cosmic rings to create a stellar blast!",
    bonusDualDamage: 25,
    bannerColor: "#3B82F6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-145",
    hero1Name: "Professor X",
    hero2Name: "Magneto",
    comboTitle: "ASTRA & MAGNETIC OMEGA COUPLING",
    comboDescription: "Charles freezes the foe's synapses while Erik crushes them in a dense metal sphere!",
    bonusDualDamage: 28,
    bannerColor: "#8B5CF6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-146",
    hero1Name: "Magneto",
    hero2Name: "Polaris",
    comboTitle: "MAGNETIC POLE INVERSION CATACLYSM",
    comboDescription: "Lorna and Erik tear the battlefield apart using Earth's planetary magnetic field!",
    bonusDualDamage: 26,
    bannerColor: "#10B981",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-147",
    hero1Name: "Gambit",
    hero2Name: "Rogue",
    comboTitle: "CHARGED TOUCH & KINETIC ACE CRUSH",
    comboDescription: "Gambit throws 52 charged aces while Rogue flies in with borrowed Captain Marvel strength!",
    bonusDualDamage: 25,
    bannerColor: "#EC4899",
    auraType: "fire",
  },
  {
    id: "combo-expansion-148",
    hero1Name: "Colossus",
    hero2Name: "Magik",
    comboTitle: "RASPUTIN SOULSWORD & STEEL VORTEX",
    comboDescription: "Magik teleports Colossus through Limbo to land crushing steel strikes from behind!",
    bonusDualDamage: 25,
    bannerColor: "#8B5CF6",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-149",
    hero1Name: "Nightcrawler",
    hero2Name: "Wolverine",
    comboTitle: "BAMF! AMBUSH CLAW STRIKE",
    comboDescription: "Nightcrawler teleports Logan through 20 dimensional coordinates in 1 second for endless slashes!",
    bonusDualDamage: 24,
    bannerColor: "#3B82F6",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-150",
    hero1Name: "Cable",
    hero2Name: "Deadpool",
    comboTitle: "CHRONO-BODYSLIDE DUAL ARMED MASSACRE",
    comboDescription: "Cable deploys future plasma rifles while Wade fires twin uzis with infinite banter!",
    bonusDualDamage: 25,
    bannerColor: "#64748B",
    auraType: "fire",
  },
  {
    id: "combo-expansion-151",
    hero1Name: "Cable",
    hero2Name: "Hope Summers",
    comboTitle: "MESSIAH OMEGA RESURRECTION FLAME",
    comboDescription: "Hope mimics Cable's telekinesis and unleashes a double telekinetic wave!",
    bonusDualDamage: 26,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-152",
    hero1Name: "Emma Frost",
    hero2Name: "Jean Grey",
    comboTitle: "PSYCHIC CEREBRO DIAMOND CRUSH",
    comboDescription: "Emma turns to diamond and pins the foe while Jean shatters their mind in the Astral Plane!",
    bonusDualDamage: 26,
    bannerColor: "#06B6D4",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-153",
    hero1Name: "Psylocke",
    hero2Name: "Angel (Archangel)",
    comboTitle: "TECHNO-ORGANIC PSYCHIC BLADE RAIN",
    comboDescription: "Archangel fires razor-sharp metallic fletchettes while Psylocke strikes with psychic katanas!",
    bonusDualDamage: 24,
    bannerColor: "#9333EA",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-154",
    hero1Name: "Storm",
    hero2Name: "Iceman",
    comboTitle: "ABSOLUTE ZERO BLIZZARD HURRICANE",
    comboDescription: "Bobby drops ambient temperature to 0 Kelvin while Storm whips up a category 5 ice blizzard!",
    bonusDualDamage: 26,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-155",
    hero1Name: "Beast",
    hero2Name: "Forge",
    comboTitle: "MUTANT INNOVATION PLASMA TRAP",
    comboDescription: "Forge crafts a neural dampener device on the fly while Hank pins the enemy with acrobatic power!",
    bonusDualDamage: 22,
    bannerColor: "#3B82F6",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-156",
    hero1Name: "Juggernaut",
    hero2Name: "Black Tom Cassidy",
    comboTitle: "CYTTORAK UNSTOPPABLE BARRICADE SMASH",
    comboDescription: "Black Tom shoots plant energy while Juggernaut barrels through at infinite momentum!",
    bonusDualDamage: 24,
    bannerColor: "#B91C1C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-157",
    hero1Name: "Mystique",
    hero2Name: "Destiny",
    comboTitle: "BROTHERHOOD PRECOGNITIVE INFILTRATION",
    comboDescription: "Destiny sees every dodge attempt 5 seconds early so Mystique lands fatal sniper shots!",
    bonusDualDamage: 23,
    bannerColor: "#2563EB",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-158",
    hero1Name: "Apocalypse",
    hero2Name: "Archangel",
    comboTitle: "DEATH HORSEMAN PROTOCOL APOCALYPSE",
    comboDescription: "Apocalypse morphs into a giant while Archangel sweeps with techno-organic wings of death!",
    bonusDualDamage: 27,
    bannerColor: "#6366F1",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-159",
    hero1Name: "Mr. Sinister",
    hero2Name: "Madelyne Pryor",
    comboTitle: "GOBLIN QUEEN CLONE GENESIS",
    comboDescription: "Sinister injects genetic mutagens while Madelyne unleashes Goblin demon magic!",
    bonusDualDamage: 25,
    bannerColor: "#DC2626",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-160",
    hero1Name: "Thanos",
    hero2Name: "Death",
    comboTitle: "COURTSHIP OF DEATH: UNIVERSAL HALVING",
    comboDescription: "Thanos offers the enemy's soul to Lady Death, causing instant percentage-based devastation!",
    bonusDualDamage: 29,
    bannerColor: "#581C87",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-161",
    hero1Name: "Thanos",
    hero2Name: "Gamora",
    comboTitle: "DEADLIEST WOMAN TITAN BEATDOWN",
    comboDescription: "Gamora strikes critical nerves while Thanos crushes with cosmic energy beams!",
    bonusDualDamage: 25,
    bannerColor: "#7E22CE",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-162",
    hero1Name: "Galactus",
    hero2Name: "Silver Surfer",
    comboTitle: "HERALD'S CALL: PLANETARY DEVOURING",
    comboDescription: "Surfer channels the Power Cosmic to immobilize the target for Galactus's planetary beam!",
    bonusDualDamage: 29,
    bannerColor: "#9333EA",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-163",
    hero1Name: "Galactus",
    hero2Name: "Cosmic Ghost Rider",
    comboTitle: "SPIRIT OF VENGEANCE POWER COSMIC",
    comboDescription: "Frank Castle fires cosmic hellfire chains while Galactus unleashes a world-destroying blast!",
    bonusDualDamage: 28,
    bannerColor: "#F97316",
    auraType: "fire",
  },
  {
    id: "combo-expansion-164",
    hero1Name: "Silver Surfer",
    hero2Name: "Adam Warlock",
    comboTitle: "SOUL GEM POWER COSMIC DISSOLUTION",
    comboDescription: "Adam Warlock traps the enemy's life-force while Surfer accelerates matter past lightspeed!",
    bonusDualDamage: 28,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-165",
    hero1Name: "Adam Warlock",
    hero2Name: "Pip the Troll",
    comboTitle: "INFINITY WATCH SPATIAL AMBUSH",
    comboDescription: "Pip teleports Adam directly behind the enemy's defenses for an unavoidable quantum beam!",
    bonusDualDamage: 23,
    bannerColor: "#D97706",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-166",
    hero1Name: "Silver Surfer",
    hero2Name: "Nova (Richard Rider)",
    comboTitle: "ANNULATION CORPS COSMIC METEOR",
    comboDescription: "Nova opens the Worldmind gate while Surfer surfs on a high-density cosmic wave!",
    bonusDualDamage: 26,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-167",
    hero1Name: "Nova (Richard Rider)",
    hero2Name: "Star-Lord",
    comboTitle: "GUARDIANS OF THE GALAXY BLASTER STORM",
    comboDescription: "Peter Quill uses dual element guns while Nova delivers a gravimetric pulse cannon strike!",
    bonusDualDamage: 24,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-168",
    hero1Name: "Star-Lord",
    hero2Name: "Gamora",
    comboTitle: "GODSLAYER SWORD & ELEMENTAL TRICK",
    comboDescription: "Peter throws gravity mines to trap the target while Gamora executes a decapitating strike!",
    bonusDualDamage: 24,
    bannerColor: "#10B981",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-169",
    hero1Name: "Rocket Raccoon",
    hero2Name: "Groot",
    comboTitle: "I AM GROOT! HEAVY HADRON ARTILLERY",
    comboDescription: "Rocket rides on Groot's shoulder firing a portable singularity cannon while Groot smashes!",
    bonusDualDamage: 25,
    bannerColor: "#15803D",
    auraType: "fire",
  },
  {
    id: "combo-expansion-170",
    hero1Name: "Drax the Destroyer",
    hero2Name: "Mantis",
    comboTitle: "EMPATHIC RAGE & DESTROYER DAGGERS",
    comboDescription: "Mantis puts the foe into an empathic trance while Drax drives twin daggers through them!",
    bonusDualDamage: 23,
    bannerColor: "#16A34A",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-171",
    hero1Name: "Knull",
    hero2Name: "Carnage",
    comboTitle: "SYMBIOTE HIVE GOD VOID EXTINCTION",
    comboDescription: "Knull swings All-Black the Necrosword as Carnage wraps the enemy in a suffocating cage!",
    bonusDualDamage: 28,
    bannerColor: "#7F1D1D",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-172",
    hero1Name: "Gorr the God Butcher",
    hero2Name: "Hela",
    comboTitle: "NECROSWORD & NECROMANCY DEATH REALM",
    comboDescription: "Gorr and Hela summon infinite black blades and Asgardian undead to impale all foes!",
    bonusDualDamage: 28,
    bannerColor: "#047857",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-173",
    hero1Name: "Loki (God of Stories)",
    hero2Name: "Thor",
    comboTitle: "YGGDRASIL BRANCH THUNDER WEAVE",
    comboDescription: "Loki rewrites the timeline to ensure Thor's thunder strike hits with guaranteed critical force!",
    bonusDualDamage: 28,
    bannerColor: "#10B981",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-174",
    hero1Name: "The One-Above-All",
    hero2Name: "Living Tribunal",
    comboTitle: "OMNIVERSAL ARBITRATION OF REALITY",
    comboDescription: "The One-Above-All and Living Tribunal judge the existence of the foe, resetting their HP!",
    bonusDualDamage: 30,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-175",
    hero1Name: "Eternity",
    hero2Name: "Infinity",
    comboTitle: "TIME & SPATIAL UNIVERSAL MERGER",
    comboDescription: "The abstract embodiments of Space and Time merge to dissolve all incoming damage!",
    bonusDualDamage: 29,
    bannerColor: "#6366F1",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-176",
    hero1Name: "God Emperor Doom",
    hero2Name: "Beyonder",
    comboTitle: "BEYONDER POWER SECRET WARS STRIKE",
    comboDescription: "Doom channels the full stolen energy of the Beyond realm, shattering the combat grid!",
    bonusDualDamage: 29,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-177",
    hero1Name: "Ultron",
    hero2Name: "Infinity Ultron",
    comboTitle: "AGE OF INFINITY NANITE VIRUS",
    comboDescription: "Ultron swarms the foe with billions of nanites while Infinity Ultron fires cosmic stone beams!",
    bonusDualDamage: 28,
    bannerColor: "#EF4444",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-178",
    hero1Name: "Kang the Conqueror",
    hero2Name: "Ravonna Renslayer",
    comboTitle: "TEMPORAL ERASURE TIME-DILATION BEAM",
    comboDescription: "Kang traps the foe in a 10-second time loop while Ravonna executes precision Tempad strikes!",
    bonusDualDamage: 26,
    bannerColor: "#15803D",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-179",
    hero1Name: "High Evolutionary",
    hero2Name: "Adam Warlock",
    comboTitle: "SOVEREIGN GENETIC COCOON BURST",
    comboDescription: "High Evolutionary boosts Adam Warlock's cellular density, triggering a quantum explosion!",
    bonusDualDamage: 26,
    bannerColor: "#A855F7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-180",
    hero1Name: "Daredevil",
    hero2Name: "Punisher",
    comboTitle: "DEVIL & THE REAPER TACTICAL CLASH",
    comboDescription: "Frank Castle lays down heavy suppressive fire while Matt Murdock maneuvers in for a takedown!",
    bonusDualDamage: 23,
    bannerColor: "#1E293B",
    auraType: "fire",
  },
  {
    id: "combo-expansion-181",
    hero1Name: "Punisher",
    hero2Name: "Ghost Rider",
    comboTitle: "HELLFIRE VENDETTA & PENANCE GAUNTLET",
    comboDescription: "Punisher unloads incendiary shotgun rounds while Ghost Rider chains the target in hellfire!",
    bonusDualDamage: 26,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-182",
    hero1Name: "Ghost Rider",
    hero2Name: "Blade",
    comboTitle: "MIDNIGHT SONS: PENANCE & SILVER SLICE",
    comboDescription: "Ghost Rider burns the target's soul with Penance Stare while Blade slices with silver swords!",
    bonusDualDamage: 25,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-183",
    hero1Name: "Blade",
    hero2Name: "Moon Knight",
    comboTitle: "MIDNIGHT SUNS: LUNAR SILVER PURGE",
    comboDescription: "Moon Knight drops crescent darts from above while Blade drives a titanium stake through the core!",
    bonusDualDamage: 24,
    bannerColor: "#E2E8F0",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-184",
    hero1Name: "Moon Knight",
    hero2Name: "Mister Knight",
    comboTitle: "KHONSHU FRACTURED MIND DUAL BEATDOWN",
    comboDescription: "Marc Spector and Steven Grant trade bodies mid-combo to overwhelm the enemy with unpredictable strikes!",
    bonusDualDamage: 24,
    bannerColor: "#F8FAFC",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-185",
    hero1Name: "Luke Cage",
    hero2Name: "Iron Fist",
    comboTitle: "HEROES FOR HIRE: STEEL CHEST DRAGON PUNCH",
    comboDescription: "Danny Rand punches Luke Cage's indestructible back, sending an amplified shockwave into the target!",
    bonusDualDamage: 25,
    bannerColor: "#EAB308",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-186",
    hero1Name: "Jessica Jones",
    hero2Name: "Luke Cage",
    comboTitle: "POWER COUPLE KINETIC SLAM",
    comboDescription: "Jessica lifts the enemy overhead and slams them into Luke's unbreakable fist!",
    bonusDualDamage: 23,
    bannerColor: "#6B7280",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-187",
    hero1Name: "Cloak",
    hero2Name: "Dagger",
    comboTitle: "LIGHT & DARKNESS HARMONIC VORTEX",
    comboDescription: "Cloak absorbs the target into the Darkforce Dimension while Dagger pierces them with light daggers!",
    bonusDualDamage: 24,
    bannerColor: "#F8FAFC",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-188",
    hero1Name: "Shang-Chi",
    hero2Name: "Iron Fist",
    comboTitle: "TEN RINGS SHOU-LAO DRAGON BLAST",
    comboDescription: "Shang-Chi commands the 10 immortal rings while Danny delivers an unstoppable Iron Fist strike!",
    bonusDualDamage: 26,
    bannerColor: "#F59E0B",
    auraType: "fire",
  },
  {
    id: "combo-expansion-189",
    hero1Name: "Shang-Chi",
    hero2Name: "Wolverine",
    comboTitle: "KUNG-FU MASTER & ADAMANTIUM KATA",
    comboDescription: "Shang-Chi redirects the enemy's balance directly onto Wolverine's extended claws!",
    bonusDualDamage: 24,
    bannerColor: "#DC2626",
    auraType: "fire",
  },
  {
    id: "combo-expansion-190",
    hero1Name: "Namor",
    hero2Name: "Doctor Doom",
    comboTitle: "CABAL ALLIANCE: ATLANTIS OCCULT BEATDOWN",
    comboDescription: "Namor summons tidal tsunami pressure while Doom unleashes high-voltage occult lightning!",
    bonusDualDamage: 26,
    bannerColor: "#0D9488",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-191",
    hero1Name: "Kingpin",
    hero2Name: "Bullseye",
    comboTitle: "CRIME SYNDICATE: DEADLY REBOUND BULLET",
    comboDescription: "Bullseye throws a deck of razor cards that bounce off Fisk's titanium cane straight into the target!",
    bonusDualDamage: 22,
    bannerColor: "#475569",
    auraType: "fire",
  },
  {
    id: "combo-expansion-192",
    hero1Name: "Green Goblin",
    hero2Name: "Doctor Octopus",
    comboTitle: "SINISTER DUO: TENTACLE GLIDER MISSILE",
    comboDescription: "Doc Ock pins the enemy with 4 adamantium tentacles while Goblin drops pumpkin bombs!",
    bonusDualDamage: 25,
    bannerColor: "#16A34A",
    auraType: "fire",
  },
  {
    id: "combo-expansion-193",
    hero1Name: "Doctor Octopus",
    hero2Name: "Electro",
    comboTitle: "HIGH-VOLTAGE BIO-METALLIC ARMATURE",
    comboDescription: "Electro charges Doc Ock's tentacles with 100,000 volts of electricity for a lethal crush!",
    bonusDualDamage: 24,
    bannerColor: "#EAB308",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-194",
    hero1Name: "Sandman",
    hero2Name: "Hydro-Man",
    comboTitle: "MUD ELEMENTAL TSUNAMI TRAP",
    comboDescription: "Sandman and Hydro-Man fuse their elemental forms into an inescapable drowning wave!",
    bonusDualDamage: 23,
    bannerColor: "#0284C7",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-195",
    hero1Name: "Rhino",
    hero2Name: "Juggernaut",
    comboTitle: "DUAL RAMMING HORNS APOCALYPSE",
    comboDescription: "Rhino and Juggernaut charge simultaneously from opposite ends, sandwiching the target!",
    bonusDualDamage: 25,
    bannerColor: "#475569",
    auraType: "fire",
  },
  {
    id: "combo-expansion-196",
    hero1Name: "Kraven the Hunter",
    hero2Name: "Vulture",
    comboTitle: "APEX HUNTER SKY DIVE TALON DROP",
    comboDescription: "Vulture lifts Kraven into the air and drops him onto the prey with poison daggers!",
    bonusDualDamage: 22,
    bannerColor: "#D97706",
    auraType: "fire",
  },
  {
    id: "combo-expansion-197",
    hero1Name: "Mysterio",
    hero2Name: "Loki",
    comboTitle: "MIRROR DIMENSION ILLUSION CAGE",
    comboDescription: "Mysterio creates holographic smoke while Loki casts real spells from within the illusions!",
    bonusDualDamage: 24,
    bannerColor: "#10B981",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-198",
    hero1Name: "Abomination",
    hero2Name: "Leader",
    comboTitle: "GAMMA CONSPIRACY MIND & MUSCLE",
    comboDescription: "Leader paralyzes the foe with mental blasts while Abomination breaks their bones!",
    bonusDualDamage: 24,
    bannerColor: "#15803D",
    auraType: "gamma",
  },
  {
    id: "combo-expansion-199",
    hero1Name: "Captain Marvel",
    hero2Name: "Ms. Marvel (Kamala Khan)",
    comboTitle: "HIGHER FURTHER FASTER HARD-LIGHT SLAM",
    comboDescription: "Kamala enlarges her fist to catch the foe while Carol drops a binary photon missile strike!",
    bonusDualDamage: 25,
    bannerColor: "#F59E0B",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-200",
    hero1Name: "Captain Marvel",
    hero2Name: "Photon (Monica Rambeau)",
    comboTitle: "ULTIMATE BINARY SPECTRUM NOVA",
    comboDescription: "Carol and Monica combine their cosmic photon fields into a stellar beam that vaporizes shields!",
    bonusDualDamage: 26,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-201",
    hero1Name: "Ms. Marvel (Kamala Khan)",
    hero2Name: "Spider-Man (Miles Morales)",
    comboTitle: "CHAMPIONS ASSEMBLE: EMBIGGENED VENOM BLITZ",
    comboDescription: "Kamala throws Miles like a dart as he charges a 100,000-volt Mega Venom Blast!",
    bonusDualDamage: 24,
    bannerColor: "#DC2626",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-202",
    hero1Name: "Nova (Sam Alexander)",
    hero2Name: "Ms. Marvel (Kamala Khan)",
    comboTitle: "CHAMPIONS CENTURION METEOR STRIKE",
    comboDescription: "Nova propels Kamala at light-speed as she embiggens her fist to crush the target!",
    bonusDualDamage: 23,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-203",
    hero1Name: "Ironheart",
    hero2Name: "Iron Man",
    comboTitle: "NEXT-GEN PRODIGY UNIBEAM CONVERGENCE",
    comboDescription: "Riri Williams and Tony Stark link arc reactors to fire an unstoppable dual plasma beam!",
    bonusDualDamage: 24,
    bannerColor: "#EC4899",
    auraType: "fire",
  },
  {
    id: "combo-expansion-204",
    hero1Name: "Ironheart",
    hero2Name: "Shuri",
    comboTitle: "HEART OF WAKANDA TECHNO-OVERDRIVE",
    comboDescription: "Riri's nanotech suit combines with Shuri's vibranium tech for an impenetrable pulse wave!",
    bonusDualDamage: 24,
    bannerColor: "#8B5CF6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-205",
    hero1Name: "Adam Warlock",
    hero2Name: "Magus",
    comboTitle: "SOUL GEM LIGHT & SHADOW SPLIT",
    comboDescription: "Adam and his dark reflection Magus rip reality apart with light and dark soul magic!",
    bonusDualDamage: 28,
    bannerColor: "#9333EA",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-206",
    hero1Name: "Silver Surfer",
    hero2Name: "Dawn Greenwood",
    comboTitle: "COSMIC BOARD EXPEDITION SHIELD",
    comboDescription: "Dawn steers the surfboard through hyperspace while Norrin Radd nullifies incoming damage!",
    bonusDualDamage: 22,
    bannerColor: "#E2E8F0",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-207",
    hero1Name: "Thor",
    hero2Name: "Odin",
    comboTitle: "ALL-FATHER & SON ASGARDIAN WRATH",
    comboDescription: "Odin channels the Odinforce through Gungnir while Thor calls down the cosmic lightning storms!",
    bonusDualDamage: 30,
    bannerColor: "#F59E0B",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-208",
    hero1Name: "Hela",
    hero2Name: "Fenris Wolf",
    comboTitle: "RAGNAROK DEATH FANGS EXECUTION",
    comboDescription: "Fenris bites down on the foe's limbs while Hela impales them with giant necro-blades!",
    bonusDualDamage: 26,
    bannerColor: "#047857",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-209",
    hero1Name: "Surtur",
    hero2Name: "Hela",
    comboTitle: "TWILIGHT SWORD ASGARDIAN DOOMSDAY",
    comboDescription: "Surtur plunges the Twilight Sword into the ground, raining eternal hellfire on all targets!",
    bonusDualDamage: 29,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-210",
    hero1Name: "Doctor Strange",
    hero2Name: "Ancient One",
    comboTitle: "EYE OF AGAMOTTO TIMELINE FUSION",
    comboDescription: "The Ancient One shatters the target's astral form while Strange binds them in temporal loops!",
    bonusDualDamage: 28,
    bannerColor: "#F59E0B",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-211",
    hero1Name: "Ghost Rider (Robbie Reyes)",
    hero2Name: "Ghost Rider (Johnny Blaze)",
    comboTitle: "HELL-CHARGER SPIRIT OF VENGEANCE DRAG-RACE",
    comboDescription: "Johnny Blaze rides his hell-cycle alongside Robbie's Dodge Charger, igniting a demonic inferno!",
    bonusDualDamage: 27,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-212",
    hero1Name: "Moon Knight",
    hero2Name: "Khonshu",
    comboTitle: "GOD OF THE MOON AVATAR VENGEANCE",
    comboDescription: "Khonshu materializes over the battlefield, crushing the foe beneath celestial lunar gravity!",
    bonusDualDamage: 28,
    bannerColor: "#E2E8F0",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-213",
    hero1Name: "Blade",
    hero2Name: "Morbius",
    comboTitle: "DAYWALKER & LIVING VAMPIRE ECLIPSE",
    comboDescription: "Morbius blinds the target with hypersonic screeches while Blade executes with silver daggers!",
    bonusDualDamage: 23,
    bannerColor: "#991B1B",
    auraType: "fire",
  },
  {
    id: "combo-expansion-214",
    hero1Name: "Punisher",
    hero2Name: "War Machine",
    comboTitle: "WAR MACHINE ARMOR URBAN PURGE",
    comboDescription: "Frank Castle pilots heavy military armor, unleashing carpet-bombing missile barrages!",
    bonusDualDamage: 25,
    bannerColor: "#334155",
    auraType: "fire",
  },
  {
    id: "combo-expansion-215",
    hero1Name: "Daredevil",
    hero2Name: "Stick",
    comboTitle: "CHASTE NINJITSU SENSORY OVERLOAD",
    comboDescription: "Stick and Matt attack blind spots with twin quarterstaves and billy clubs in flawless unison!",
    bonusDualDamage: 22,
    bannerColor: "#DC2626",
    auraType: "fire",
  },
  {
    id: "combo-expansion-216",
    hero1Name: "Elektra",
    hero2Name: "Bullseye",
    comboTitle: "ASSASSIN'S RIVALRY FATAL STRIKE",
    comboDescription: "Twin assassins trade deadly throws, turning the opponent's body into a pincushion!",
    bonusDualDamage: 23,
    bannerColor: "#991B1B",
    auraType: "fire",
  },
  {
    id: "combo-expansion-217",
    hero1Name: "Kingpin",
    hero2Name: "Hammerhead",
    comboTitle: "MAGGIA CRIME SYNDICATE SLEDGEHAMMER",
    comboDescription: "Hammerhead headbutts with his adamantium skull while Kingpin delivers a bone-shattering bearhug!",
    bonusDualDamage: 23,
    bannerColor: "#475569",
    auraType: "fire",
  },
  {
    id: "combo-expansion-218",
    hero1Name: "Kraven the Hunter",
    hero2Name: "Chameleon",
    comboTitle: "SINISTER SIBLINGS JUNGLE TRAP",
    comboDescription: "Chameleon distracts the target in disguise while Kraven ambushes with paralyzing blowdarts!",
    bonusDualDamage: 22,
    bannerColor: "#D97706",
    auraType: "fire",
  },
  {
    id: "combo-expansion-219",
    hero1Name: "Scorpion",
    hero2Name: "Rhino",
    comboTitle: "SINISTER SYNDICATE ACID CRUSH",
    comboDescription: "Scorpion sprays concentrated acid while Rhino rams the weakened target into rubble!",
    bonusDualDamage: 23,
    bannerColor: "#16A34A",
    auraType: "fire",
  },
  {
    id: "combo-expansion-220",
    hero1Name: "Vulture",
    hero2Name: "Electro",
    comboTitle: "ELECTRO-MAGNETIC TALON DIVE",
    comboDescription: "Vulture dives at terminal velocity with talons energized by Electro's lightning bolts!",
    bonusDualDamage: 23,
    bannerColor: "#EAB308",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-221",
    hero1Name: "Shocker",
    hero2Name: "Electro",
    comboTitle: "SEISMIC VOLT OVERLOAD SHOCKWAVE",
    comboDescription: "Shocker's vibro-gauntlets amplify Electro's lightning into a localized tectonic earthquake!",
    bonusDualDamage: 23,
    bannerColor: "#EAB308",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-222",
    hero1Name: "Hobgoblin",
    hero2Name: "Green Goblin",
    comboTitle: "TWIN GLIDER PUMPKIN CARPET BOMB",
    comboDescription: "Both goblins fly overhead in tight formation, dropping a grid of incendiary sonic bombs!",
    bonusDualDamage: 25,
    bannerColor: "#F97316",
    auraType: "fire",
  },
  {
    id: "combo-expansion-223",
    hero1Name: "Doc Ock",
    hero2Name: "Mysterio",
    comboTitle: "ILLUSORY TENTACLE CHOKE-SLAM",
    comboDescription: "Mysterio hides the tentacles inside holographic dragons, snatching the foe by surprise!",
    bonusDualDamage: 24,
    bannerColor: "#10B981",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-224",
    hero1Name: "Sandman",
    hero2Name: "Venom",
    comboTitle: "SYMBIOTE SANDSTORM EXTINCTION",
    comboDescription: "Venom bonds with Sandman's particles, turning the entire arena into a living predator storm!",
    bonusDualDamage: 25,
    bannerColor: "#334155",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-225",
    hero1Name: "Carnage",
    hero2Name: "Shriek",
    comboTitle: "MAXIMUM CARNAGE SONIC BLOOD SHEDS",
    comboDescription: "Shriek releases brain-scrambling sonic screams while Carnage shreds with scythe arms!",
    bonusDualDamage: 24,
    bannerColor: "#991B1B",
    auraType: "symbiote",
  },
  {
    id: "combo-expansion-226",
    hero1Name: "Mister Sinister",
    hero2Name: "Mystique",
    comboTitle: "BROTHERHOOD DNA RECOMBINATION",
    comboDescription: "Sinister clones Mystique mid-combat to create a squad of lethal shapeshifting assassins!",
    bonusDualDamage: 25,
    bannerColor: "#2563EB",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-227",
    hero1Name: "Magneto",
    hero2Name: "Juggernaut",
    comboTitle: "BROTHERHOOD CATACLYSM SIEGE",
    comboDescription: "Magneto accelerates Juggernaut using electromagnetic propulsion into an unstoppable bullet!",
    bonusDualDamage: 27,
    bannerColor: "#DC2626",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-228",
    hero1Name: "Emma Frost",
    hero2Name: "Sebastian Shaw",
    comboTitle: "HELLFIRE CLUB KINETIC DIAMOND ABSORB",
    comboDescription: "Emma directs enemy strikes onto Shaw, who absorbs the kinetic force to hit with 10x power!",
    bonusDualDamage: 25,
    bannerColor: "#B45309",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-229",
    hero1Name: "Sunspot",
    hero2Name: "Cannonball",
    comboTitle: "NEW MUTANTS SOLAR BLASTIN' METEOR",
    comboDescription: "Cannonball becomes thermo-chemically invulnerable while Sunspot superheats his flight path!",
    bonusDualDamage: 24,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-230",
    hero1Name: "Magik",
    hero2Name: "Wolfsbane",
    comboTitle: "NEW MUTANTS LIMBO FERAL AMBUSH",
    comboDescription: "Magik teleports Rahne Sinclair in werewolf form directly onto the enemy's throat!",
    bonusDualDamage: 23,
    bannerColor: "#8B5CF6",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-231",
    hero1Name: "Mirage (Dani Moonstar)",
    hero2Name: "Magik",
    comboTitle: "VALKYRIE SOUL FEAR MANIFESTATION",
    comboDescription: "Dani projects the target's greatest nightmare as Magik cleaves their soul with her Soulsword!",
    bonusDualDamage: 25,
    bannerColor: "#8B5CF6",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-232",
    hero1Name: "Warlock (Technarch)",
    hero2Name: "Cypher",
    comboTitle: "DOUGLOCK TECHNO-ORGANIC OMNIGLOT",
    comboDescription: "Warlock fuses with Cypher to instantly translate and disable the enemy's combat programming!",
    bonusDualDamage: 24,
    bannerColor: "#EAB308",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-233",
    hero1Name: "Bishop",
    hero2Name: "Cable",
    comboTitle: "CHRONO-COPS FUTURE ENERGY DISCHARGE",
    comboDescription: "Bishop absorbs the foe's energy attack and channels it directly into Cable's plasma cannon!",
    bonusDualDamage: 25,
    bannerColor: "#EF4444",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-234",
    hero1Name: "Havok",
    hero2Name: "Polaris",
    comboTitle: "COSMIC PLASMA & MAGNETIC FLUX TORNADO",
    comboDescription: "Alex and Lorna combine cosmic rays and magnetic currents into a glowing vortex of destruction!",
    bonusDualDamage: 26,
    bannerColor: "#10B981",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-235",
    hero1Name: "Iceman",
    hero2Name: "Human Torch",
    comboTitle: "FIRE & ICE THERMODYNAMIC SHOCK",
    comboDescription: "Human Torch superheats the target to Nova heat, followed instantly by Iceman's 0-Kelvin freeze!",
    bonusDualDamage: 27,
    bannerColor: "#F97316",
    auraType: "fire",
  },
  {
    id: "combo-expansion-236",
    hero1Name: "Mr. Fantastic",
    hero2Name: "Invisible Woman",
    comboTitle: "FANTASTIC FOUR ELASTIC FORCE-SPHERE",
    comboDescription: "Sue traps the enemy in an invisible force field while Reed coils around it to compress and crush!",
    bonusDualDamage: 26,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-237",
    hero1Name: "Thing",
    hero2Name: "Human Torch",
    comboTitle: "IT'S CLOBBERIN' TIME NOVA TACKLE",
    comboDescription: "Johnny ignites Thing into a flaming meteor rock that tackles the foe through 5 skyscrapers!",
    bonusDualDamage: 26,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-238",
    hero1Name: "Mr. Fantastic",
    hero2Name: "Thing",
    comboTitle: "FANTASTIC SLINGSHOT CLOBBERIN' CANNON",
    comboDescription: "Reed stretches into a 100-foot slingshot and launches Ben Grimm at Mach 5!",
    bonusDualDamage: 25,
    bannerColor: "#D97706",
    auraType: "fire",
  },
  {
    id: "combo-expansion-239",
    hero1Name: "Invisible Woman",
    hero2Name: "Namor",
    comboTitle: "FORCE-FIELD TIDAL SURGE",
    comboDescription: "Sue creates microscopic invisible barriers to funnel Namor's oceanic trident with lethal focus!",
    bonusDualDamage: 25,
    bannerColor: "#0284C7",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-240",
    hero1Name: "Silver Surfer",
    hero2Name: "Mr. Fantastic",
    comboTitle: "COSMIC REED ULTIMATE NULLIFIER CALCULATION",
    comboDescription: "Reed computes the exact quantum coordinates as Surfer fires pure Power Cosmic energy!",
    bonusDualDamage: 28,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-241",
    hero1Name: "Doctor Doom",
    hero2Name: "Kangaroo",
    comboTitle: "DOOM'S LATVERIAN HIGH-JUMP AMBUSH",
    comboDescription: "Doctor Doom implants cyber-enhancers into Kangaroo for an absurd yet devastating air-drop strike!",
    bonusDualDamage: 20,
    bannerColor: "#15803D",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-242",
    hero1Name: "Doctor Doom",
    hero2Name: "Magneto",
    comboTitle: "PRIME MINISTERS OF DOOM & STEEL",
    comboDescription: "Magneto tears apart metallic weaponry while Doom channels mystic lightning through the debris!",
    bonusDualDamage: 28,
    bannerColor: "#6366F1",
    auraType: "lightning",
  },
  {
    id: "combo-expansion-243",
    hero1Name: "Doctor Doom",
    hero2Name: "Loki",
    comboTitle: "LORDS OF SORCERY REALITY SUBVERSION",
    comboDescription: "Loki distorts perception with Asgardian glamours as Doom casts the spell of Molecular Decay!",
    bonusDualDamage: 27,
    bannerColor: "#10B981",
    auraType: "chaos",
  },
  {
    id: "combo-expansion-244",
    hero1Name: "Loki (God of Stories)",
    hero2Name: "Sylvie",
    comboTitle: "MULTIVERSAL LOOM REWRITING",
    comboDescription: "Loki and Sylvie sever the enemy's timeline branch, wiping out their bonus stats!",
    bonusDualDamage: 28,
    bannerColor: "#10B981",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-245",
    hero1Name: "Kang the Conqueror",
    hero2Name: "Immortus",
    comboTitle: "TIME-COUNCIL TEMPORAL PARADOX",
    comboDescription: "Immortus and Kang trap the target between past and future, causing chronal disintegration!",
    bonusDualDamage: 27,
    bannerColor: "#8B5CF6",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-246",
    hero1Name: "Galactus",
    hero2Name: "Terrax",
    comboTitle: "HERALD OF ROCK PLANETARY CRACKER",
    comboDescription: "Terrax splits the tectonic crust of the planet allowing Galactus to feed instantly!",
    bonusDualDamage: 27,
    bannerColor: "#78716C",
    auraType: "cosmic",
  },
  {
    id: "combo-expansion-247",
    hero1Name: "Galactus",
    hero2Name: "Firelord",
    comboTitle: "HERALD OF COSMIC FIRE CLEANSING",
    comboDescription: "Firelord summons a cosmic solar storm that melts the opponent's armor for Galactus!",
    bonusDualDamage: 27,
    bannerColor: "#EA580C",
    auraType: "fire",
  },
  {
    id: "combo-expansion-248",
    hero1Name: "Gorr the God Butcher",
    hero2Name: "Knull",
    comboTitle: "ALL-BLACK NECROSWORD HIVE ECLIPSE",
    comboDescription: "Gorr and Knull swing twin necro-blades, devouring all divine and mortal light in the arena!",
    bonusDualDamage: 30,
    bannerColor: "#000000",
    auraType: "symbiote",
  },
  {
    id: "duo-230",
    hero1Name: "Silver Surfer",
    hero2Name: "Galactus",
    comboTitle: "HERALD OF THE COSMIC DEVOURER",
    comboDescription: "Silver Surfer channels the Power Cosmic as Galactus unleashes celestial world-devouring energy!",
    bonusDualDamage: 30,
    bannerColor: "#38BDF8",
    auraType: "cosmic",
  },
];

export function getActiveTagTeamCombos(collection: Character[]): TagTeamCombo[] {
  const active: TagTeamCombo[] = [];
  if (!collection || !Array.isArray(collection)) return active;
  const names = collection.filter(Boolean).map(c => (c.name || '').toLowerCase());

  TAG_TEAM_COMBOS.forEach(combo => {
    const hasH1 = names.some(n => n.includes(combo.hero1Name.toLowerCase()) || combo.hero1Name.toLowerCase().includes(n));
    const hasH2 = names.some(n => n.includes(combo.hero2Name.toLowerCase()) || combo.hero2Name.toLowerCase().includes(n));
    if (hasH1 && hasH2) {
      active.push(combo);
    }
  });

  return active;
}

export function getFighterTagTeamCombo(fighter: Character, team: Character[]): TagTeamCombo | null {
  if (!fighter || !fighter.name || !team || !Array.isArray(team)) return null;
  const fighterName = fighter.name.toLowerCase();
  const teamNames = team.filter(Boolean).map(c => (c.name || '').toLowerCase());

  for (const combo of TAG_TEAM_COMBOS) {
    const h1 = combo.hero1Name.toLowerCase();
    const h2 = combo.hero2Name.toLowerCase();

    const isH1 = fighterName.includes(h1) || h1.includes(fighterName);
    const isH2 = fighterName.includes(h2) || h2.includes(fighterName);

    if (isH1) {
      if (teamNames.some(n => n.includes(h2) || h2.includes(n))) {
        return combo;
      }
    } else if (isH2) {
      if (teamNames.some(n => n.includes(h1) || h1.includes(n))) {
        return combo;
      }
    }
  }

  return null;
}

export function findPossibleTagTeamFusions(roster: Character[]): { hero1: Character; hero2: Character; combo: TagTeamCombo }[] {
  const fusions: { hero1: Character; hero2: Character; combo: TagTeamCombo }[] = [];
  if (!roster || roster.length < 2) return fusions;

  for (let i = 0; i < roster.length; i++) {
    for (let j = i + 1; j < roster.length; j++) {
      const h1 = roster[i];
      const h2 = roster[j];
      if (!h1 || !h2) continue;

      const combo = getFighterTagTeamCombo(h1, [h2]);
      if (combo) {
        fusions.push({ hero1: h1, hero2: h2, combo });
      }
    }
  }

  return fusions;
}

export function mergeUltimateCharacter(hero1: Character, hero2: Character, combo: TagTeamCombo): Character {
  // Overcharged Fusion Power: Greater than individual heroes + full synergy amplification
  const baseHighest = Math.max(hero1.overallPower, hero2.overallPower);
  const mergedPower = Math.min(100, baseHighest + Math.round(combo.bonusDualDamage * 0.75) + 5);

  return {
    id: `fusion-${hero1.id}-${hero2.id}`,
    name: `${hero1.name} & ${hero2.name}`,
    alias: `⚡ ${combo.comboTitle}`,
    grade: "MYTHIC",
    alignment: hero1.alignment || hero2.alignment || 'Hero',
    startingPrice: Math.max(hero1.startingPrice, hero2.startingPrice) + 15,
    powers: `DUAL OVERDRIVE: ${hero1.powers} combined with ${hero2.powers}. Synchronized Ultimate: ${combo.comboDescription}`,
    description: `⚡ LEGENDARY TAG-TEAM FUSION: ${combo.comboTitle}. Deals massive amplified combo damage, combined vitality, and dual super moves!`,
    color: combo.bannerColor || '#EC4899',
    imageUrl: hero1.imageUrl || hero2.imageUrl,
    overallPower: mergedPower,
    stats: {
      strength: Math.min(100, Math.round((hero1.stats.strength + hero2.stats.strength) * 0.72)),
      speed: Math.min(100, Math.round((hero1.stats.speed + hero2.stats.speed) * 0.72)),
      durability: Math.min(100, Math.round((hero1.stats.durability + hero2.stats.durability) * 0.72)),
      intelligence: Math.min(100, Math.max(hero1.stats.intelligence, hero2.stats.intelligence) + 8),
      energy: Math.min(100, Math.max(hero1.stats.energy, hero2.stats.energy) + 12),
      combat: Math.min(100, Math.max(hero1.stats.combat, hero2.stats.combat) + 10),
    },
    specialAbilities: [
      {
        name: `💥 DUAL FINISHER: ${combo.comboTitle}`,
        description: `Unleashes coordinated dual-hero assault dealing ${combo.bonusDualDamage + 10} catastrophic combo strike damage!`,
        bonusPower: combo.bonusDualDamage + 10,
        triggerRate: 0.95,
        type: "cosmic",
      },
      {
        name: `🛡️ HARMONIC BARRIER`,
        description: `Overlapping forcefields absorb incoming damage and redirect kinetic force.`,
        bonusPower: 12,
        triggerRate: 0.85,
        type: "defense",
      },
      {
        name: `⚡ SYNCHRONIZED RUSH`,
        description: `High-speed flanking blitz bypasses opponent evasion.`,
        bonusPower: 14,
        triggerRate: 0.85,
        type: "tactical",
      },
      ...(hero1.specialAbilities || []).slice(0, 2),
      ...(hero2.specialAbilities || []).slice(0, 2),
    ]
  };
}



